module: stats: fix invalid_mod_bytes typo
Jira: http://issues.redhat.com/28063

commit a81b1fc8ea639e03326c1d0dcde041986bc11500
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Apr 18 09:17:51 2023 +0200

    module: stats: fix invalid_mod_bytes typo

    This was caught by randconfig builds but does not show up in
    build testing without CONFIG_MODULE_DECOMPRESS:

    kernel/module/stats.c: In function 'mod_stat_bump_invalid':
    kernel/module/stats.c:229:42: error: 'invalid_mod_byte' undeclared (first use in this function); did you mean 'invalid_mod_bytes'?
      229 |   atomic_long_add(info->compressed_len, &invalid_mod_byte);
          |                                          ^~~~~~~~~~~~~~~~
          |                                          invalid_mod_bytes

    Fixes: df3e764d8e5c ("module: add debug stats to help identify memory pressure")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>