xfs: fix uninit warning in xfs_growfs_data
JIRA: https://issues.redhat.com/browse/RHEL-25419

commit ed04a91f718e6e1ab82d47a22b26e4b50c1666f6
Author: Darrick J. Wong <djwong@kernel.org>
Date:   Thu Jul 6 18:00:59 2023 -0700

    xfs: fix uninit warning in xfs_growfs_data

    Quiet down this gcc warning:

    fs/xfs/xfs_fsops.c: In function ‘xfs_growfs_data’:
    fs/xfs/xfs_fsops.c:219:21: error: ‘lastag_extended’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      219 |                 if (lastag_extended) {
          |                     ^~~~~~~~~~~~~~~
    fs/xfs/xfs_fsops.c:100:33: note: ‘lastag_extended’ was declared here
      100 |         bool                    lastag_extended;
          |                                 ^~~~~~~~~~~~~~~

    By setting its value explicitly.  From code analysis I don't think this
    is a real problem, but I have better things to do than analyse this
    closely.

    Signed-off-by: Darrick J. Wong <djwong@kernel.org>
    Reviewed-by: Dave Chinner <dchinner@redhat.com>

Signed-off-by: Bill O'Donnell <bodonnel@redhat.com>