tty: serial: samsung: Fix driver data macros style
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit f63299b3972d07c3c436fc13949d05d8dcf5e41c
Author: Sam Protsenko <semen.protsenko@linaro.org>
Date:   Wed Aug 11 14:48:25 2021 +0300

    tty: serial: samsung: Fix driver data macros style

    Make checkpatch happy by fixing this error:

        ERROR: Macros with complex values should be enclosed in parentheses

    Although this change is made to keep macros consistent with consequent
    patches (adding driver data for new SoC), it's intentionally added as a
    separate patch to ease possible porting efforts in future.

    Reviewed-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    Link: https://lore.kernel.org/r/20210811114827.27322-6-semen.protsenko@linaro.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>