ata: pata_macio: Add explicit include of irqdomain.h
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit cf02f71c3ef870f0376a723fd9c95d288f381984
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:19 2023 -0500

    ata: pata_macio: Add explicit include of irqdomain.h

    With linux/acpi.h no longer including irqdomain.h, add an explicit
    include of irqdomain.h to fix the following error:

    drivers/ata/pata_macio.c:1172:23: error: implicit declaration of function 'irq_create_mapping' [-Werror=implicit-function-declaration]

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>