staging: iio: resolver: ad2s1210: Add explicit include for of.h
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 98aeb3b0b6bd2704b2c687b084eeebdee49b073b
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:16 2023 -0500

    staging: iio: resolver: ad2s1210: Add explicit include for of.h

    With linux/acpi.h no longer implicitly including of.h, add an explicit
    include of of.h to fix the following error:

    drivers/staging/iio/resolver/ad2s1210.c:706:21: error: implicit declaration of function 'of_match_ptr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

    Acked-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
    Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
    Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>