samples/bpf: Fix application of sizeof to pointer
Bugzilla: https://bugzilla.redhat.com/2041365

commit b599015f044df53e93ad0a2957b615bc1a26bf73
Author: David Yang <davidcomponentone@gmail.com>
Date:   Tue Oct 12 19:16:49 2021 +0800

    samples/bpf: Fix application of sizeof to pointer

    The coccinelle check report:
    "./samples/bpf/xdp_redirect_cpu_user.c:397:32-38:
    ERROR: application of sizeof to pointer"
    Using the "strlen" to fix it.

    Reported-by: Zeal Robot <zealci@zte.com.cn>
    Signed-off-by: David Yang <davidcomponentone@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20211012111649.983253-1-davidcomponentone@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>