coresight: Fix signedness bug in tmc_etr_buf_insert_barrier_packet()
JIRA: https://issues.redhat.com/browse/RHEL-21456

commit f67bc15e526bb9920683ad6c1891ff9e08981335
Author: Dan Carpenter <dan.carpenter@linaro.org>
Date: Fri, 21 Apr 2023 13:42:41 +0300

    This code generates a Smatch warning:

        drivers/hwtracing/coresight/coresight-tmc-etr.c:947 tmc_etr_buf_insert_barrier_packet()
        error: uninitialized symbol 'bufp'.

    The problem is that if tmc_sg_table_get_data() returns -EINVAL, then
    when we test if "len < CORESIGHT_BARRIER_PKT_SIZE", the negative "len"
    value is type promoted to a high unsigned long value which is greater
    than CORESIGHT_BARRIER_PKT_SIZE.  Fix this bug by adding an explicit
    check for error codes.

    Fixes: 75f4e3619fe2 ("coresight: tmc-etr: Add transparent buffer management")
    Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
    Signed-off-by: Suzuki K Poulose <suzuki.poulose@arm.com>
    Link: https://lore.kernel.org/r/7d33e244-d8b9-4c27-9653-883a13534b01@kili.mountain

Signed-off-by: Mark Salter <msalter@redhat.com>