nvme: target: fix nvme_keyring_id() references
JIRA: https://issues.redhat.com/browse/RHEL-25547

In configurations without CONFIG_NVME_TARGET_TCP_TLS, the keyring
code might not be available, or using it will result in a runtime
failure:

x86_64-linux-ld: vmlinux.o: in function `nvmet_ports_make':
configfs.c:(.text+0x100a211): undefined reference to `nvme_keyring_id'

Add a check to ensure we only check the keyring if there is a chance
of it being used, which avoids both the runtime and link-time
problems.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20231122224719.4042108-2-arnd@kernel.org
Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit d78abcbabe7e98bb4baa4dea87550806944790ed)
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>