serial: imx: remove unused imx_uart_is_imx* functions
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 7553574900f37847a25c4d572b13c512811604ed
Author: Tom Rix <trix@redhat.com>
Date:   Fri Mar 17 16:57:10 2023 -0400

    serial: imx: remove unused imx_uart_is_imx* functions

    clang with W=1 reports
    drivers/tty/serial/imx.c:292:19: error:
      unused function 'imx_uart_is_imx21' [-Werror,-Wunused-function]
    static inline int imx_uart_is_imx21(struct imx_port *sport)
                      ^
    drivers/tty/serial/imx.c:297:19: error:
      unused function 'imx_uart_is_imx53' [-Werror,-Wunused-function]
    static inline int imx_uart_is_imx53(struct imx_port *sport)
                      ^
    drivers/tty/serial/imx.c:302:19: error:
      unused function 'imx_uart_is_imx6q' [-Werror,-Wunused-function]
    static inline int imx_uart_is_imx6q(struct imx_port *sport)
                      ^
    These static functions are not used, so remove them.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
    Link: https://lore.kernel.org/r/20230317205710.1672232-1-trix@redhat.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>