Documentation: add pyyaml to requirements.txt
JIRA: https://issues.redhat.com/browse/RHEL-30145

Conflicts:
- adjusted context conflict due to missing df19817f3ff3de ("docs:
  sphinx-pre-install: don't require the RTD theme")

Upstream commit(s):
commit 7df54188a897ff656e237239f2b02a8f70183333
Author: Vegard Nossum <vegard.nossum@oracle.com>
Date:   Fri Dec 22 14:36:28 2023 +0100

    Documentation: add pyyaml to requirements.txt

    Commit f061c9f7d058 ("Documentation: Document each netlink family") added
    a new Python script that is invoked during 'make htmldocs' and which reads
    the netlink YAML spec files.

    Using the virtualenv from scripts/sphinx-pre-install, we get this new
    error wen running 'make htmldocs':

      Traceback (most recent call last):
        File "./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>
          import yaml
      ModuleNotFoundError: No module named 'yaml'
      make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/rt_link.rst] Error 1
      make[1]: *** [Makefile:1708: htmldocs] Error 2

    Fix this by adding 'pyyaml' to requirements.txt.

    Note: This was somehow present in the original patch submission:
    <https://lore.kernel.org/all/20231103135622.250314-1-leitao@debian.org/>
    I'm not sure why the pyyaml requirement disappeared in the meantime.

    Fixes: f061c9f7d058 ("Documentation: Document each netlink family")
    Cc: Breno Leitao <leitao@debian.org>
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: David S. Miller <davem@davemloft.net>
    Cc: Jonathan Corbet <corbet@lwn.net>
    Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>