efi: sysfb_efi: fix build when EFI is not set
Bugzilla: http://bugzilla.redhat.com/1986223

commit 15d27b15de965043d6f8e23bc7f34386fcd1a772
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Mon Jul 26 22:04:47 2021 -0700

    efi: sysfb_efi: fix build when EFI is not set

    When # CONFIG_EFI is not set, there are 2 definitions of
    sysfb_apply_efi_quirks(). The stub from sysfb.h should be used
    and the __init function from sysfb_efi.c should not be used.

    ../drivers/firmware/efi/sysfb_efi.c:337:13: error: redefinition of ‘sysfb_apply_efi_quirks’
     __init void sysfb_apply_efi_quirks(struct platform_device *pd)
                 ^~~~~~~~~~~~~~~~~~~~~~
    In file included from ../drivers/firmware/efi/sysfb_efi.c:26:0:
    ../include/linux/sysfb.h:65:20: note: previous definition of ‘sysfb_apply_efi_quirks’ was here
     static inline void sysfb_apply_efi_quirks(struct platform_device *pd)
                        ^~~~~~~~~~~~~~~~~~~~~~

    Reviewed-by: Javier Martinez Canillas <javierm@redhat.com>
    Fixes: 8633ef82f101 ("drivers/firmware: consolidate EFI framebuffer setup for all arches")
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Ard Biesheuvel <ardb@kernel.org>
    Cc: linux-efi@vger.kernel.org
    Cc: dri-devel@lists.freedesktop.org
    Cc: Javier Martinez Canillas <javierm@redhat.com>
    Cc: Thomas Zimmermann <tzimmermann@suse.de>
    Cc: Mark Brown <broonie@kernel.org>
    Cc: linux-next@vger.kernel.org
    Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
    Link: https://patchwork.freedesktop.org/patch/msgid/20210727050447.7339-1-rdunlap@infradead.org

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>