mlx5: Fix type of mode parameter in mlx5_dpll_device_mode_get()
JIRA: https://issues.redhat.com/browse/RHEL-24466
Upstream-status: v6.7-rc1

commit f4ecb3d44a117b16029485325bda1bc98c26de36
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Oct 2 13:55:21 2023 -0700

    mlx5: Fix type of mode parameter in mlx5_dpll_device_mode_get()

    When building with -Wincompatible-function-pointer-types-strict, a
    warning designed to catch potential kCFI failures at build time rather
    than run time due to incorrect function pointer types, there is a
    warning due to a mismatch between the type of the mode parameter in
    mlx5_dpll_device_mode_get() vs. what the function pointer prototype for
    ->mode_get() in 'struct dpll_device_ops' expects.

      drivers/net/ethernet/mellanox/mlx5/core/dpll.c:141:14: error: incompatible function pointer types initializing 'int (*)(const struct dpll_device *, void *, enum dpll_mode *, struct netlink_ext_ack *)' with an expression of type 'int (const struct dpll_device *, void *, u32 *, struct netlink_ext_ack *)' (aka 'int (const struct dpll_device *, void *, unsigned int *, struct netlink_ext_ack *)') [-Werror,-Wincompatible-function-pointer-types-strict]
        141 |         .mode_get = mlx5_dpll_device_mode_get,
            |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.

    Change the type of the mode parameter in mlx5_dpll_device_mode_get() to
    clear up the warning and avoid kCFI failures at run time.

    Fixes: 496fd0a26bbf ("mlx5: Implement SyncE support using DPLL infrastructure")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Link: https://lore.kernel.org/r/20231002-net-wifpts-dpll_mode_get-v1-2-a356a16413cf@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Benjamin Poirier <bpoirier@nvidia.com>