platform/olpc: olpc-xo175-ec: Use SPI device ID data to bind device
JIRA: https://issues.redhat.com/browse/RHEL-33550

commit d7b2b9387edac5a93058dcbf9b70017a764bfd18
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Mon, 20 Mar 2023 14:43:35 +0000

The driver defines spi_device_id table for module autoloading, but does
not use it in id_table which causes W=1 warning:

  drivers/platform/olpc/olpc-xo175-ec.c:737:35: error: ‘olpc_xo175_ec_id_table’ defined but not used [-Werror=unused-const-variable=]

Reference the SPI device ID table, so it can be also used for device
binding.

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>

Link: https://lore.kernel.org/r/20230316160324.78856-1-krzysztof.kozlowski@linaro.org
Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>