tools: ynl: support pretty printing bad attribute names
JIRA: https://issues.redhat.com/browse/RHEL-30344

commit 4cd2796f3f8d82aa3a13d3eca39950fe6fe9d672
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Mon Jan 30 18:33:48 2023 -0800

    tools: ynl: support pretty printing bad attribute names

    One of my favorite features of the Netlink specs is that they
    make decoding structured extack a ton easier.
    Implement pretty printing bad attribute names in YNL.

    For example it will now say:

      'bad-attr': '.header.flags'

    rather than the useless:

      'bad-attr-offs': 32

    Proof:

      $ ./cli.py --spec ethtool.yaml --do rings_get \
         --json '{"header":{"dev-index":1, "flags":4}}'
      Netlink error: Invalid argument
      nl_len = 68 (52) nl_flags = 0x300 nl_type = 2
            error: -22      extack: {'msg': 'reserved bit set',
                                     'bad-attr': '.header.flags'}

    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>