Revert "tty: serial: fsl_lpuart: adjust SERIAL_FSL_LPUART_CONSOLE config dependency"
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 2d638be71155b2e036aca1966b6129e2d661e91f
Author: Tom Rix <trix@redhat.com>
Date:   Sun Feb 26 12:38:46 2023 -0500

    Revert "tty: serial: fsl_lpuart: adjust SERIAL_FSL_LPUART_CONSOLE config dependency"

    This reverts commit 5779a072c248db7a40cfd0f5ea958097fd1d9a30.

    This results in a link error of

    ld: drivers/tty/serial/earlycon.o: in function `parse_options':
    drivers/tty/serial/earlycon.c:99: undefined reference to `uart_parse_earlycon'

    When the config is in this state

    CONFIG_SERIAL_CORE=m
    CONFIG_SERIAL_CORE_CONSOLE=y
    CONFIG_SERIAL_EARLYCON=y
    CONFIG_SERIAL_FSL_LPUART=m
    CONFIG_SERIAL_FSL_LPUART_CONSOLE=y

    Fixes: 5779a072c248 ("tty: serial: fsl_lpuart: adjust SERIAL_FSL_LPUART_CONSOLE config dependency")
    Cc: stable <stable@kernel.org>
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Jiri Slaby <jirislaby@kernel.org>
    Link: https://lore.kernel.org/r/20230226173846.236691-1-trix@redhat.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>