tools: ynl: add more info to KeyErrors on missing attrs
JIRA: https://issues.redhat.com/browse/RHEL-30656

commit 7582113c6917c280c90352d1935cfa451e74376a
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Mon Aug 14 13:56:27 2023 -0700

    tools: ynl: add more info to KeyErrors on missing attrs

    When developing specs its useful to know which attr space
    YNL was trying to find an attribute in on key error.

    Instead of printing:
     KeyError: 0
    add info about the space:
     Exception: Space 'vport' has no attribute with value '0'

    Reviewed-by: Donald Hunter <donald.hunter@gmail.com>
    Link: https://lore.kernel.org/r/20230814205627.2914583-4-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>