netfs: Eliminate Clang randstruct warning
Bugzilla: http://bugzilla.redhat.com/1229736

commit 3b5eed3c71a2fb60aa4405ad92a2a6ad2677f220
Author: Kees Cook <keescook@chromium.org>
Date:   Tue May 3 13:54:58 2022 -0700

    netfs: Eliminate Clang randstruct warning

    Clang's structure layout randomization feature gets upset when it sees
    struct inode (which is randomized) cast to struct netfs_i_context. This
    is due to seeing the inode pointer as being treated as an array of inodes,
    rather than "something else, following struct inode".

    Since netfs can't use container_of() (since it doesn't know what the
    true containing struct is), it uses this direct offset instead. Adjust
    the code to better reflect what is happening: an arbitrary pointer is
    being adjusted and cast to something else: use a "void *" for the math.
    The resulting binary output is the same, but Clang no longer sees an
    unexpected cross-structure cast:

    In file included from ../fs/nfs/inode.c:50:
    In file included from ../fs/nfs/fscache.h:15:
    In file included from ../include/linux/fscache.h:18:
    ../include/linux/netfs.h:298:9: error: casting from randomized structure pointer type 'struct inode *' to 'struct netfs_i_context *'
            return (struct netfs_i_context *)(inode + 1);
                   ^
    1 error generated.

    Cc: David Howells <dhowells@redhat.com>
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Link: https://lore.kernel.org/r/20220503205503.3054173-2-keescook@chromium.org
    Reviewed-by: Jeff Layton <jlayton@kernel.org>
    Link: https://lore.kernel.org/lkml/7562f8eccd7cc0e447becfe9912179088784e3b9.camel@kernel.org

Signed-off-by: Jeffrey Layton <jlayton@redhat.com>