netfilter: nf_tables: don't use 'data_size' uninitialized
JIRA: https://issues.redhat.com/browse/RHEL-17446
Upstream Status: commit 63045bfd3c8d

commit 63045bfd3c8dbe9c8bee7e33291202725154cb2c
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Mon Jan 10 19:33:36 2022 -0800

    netfilter: nf_tables: don't use 'data_size' uninitialized

    Commit 2c865a8a28a1 ("netfilter: nf_tables: add rule blob layout") never
    initialized the new 'data_size' variable.

    I'm not sure how it ever worked, but it might have worked almost by
    accident - gcc seems to occasionally miss these kinds of 'variable used
    uninitialized' situations, but I've seen it do so because it ended up
    zero-initializing them due to some other simplification.

    But clang is very unhappy about it all, and correctly reports

        net/netfilter/nf_tables_api.c:8278:4: error: variable 'data_size' is uninitialized when used here [-Werror,-Wuninitialized]
                                data_size += sizeof(*prule) + rule->dlen;
                                ^~~~~~~~~
        net/netfilter/nf_tables_api.c:8263:30: note: initialize the variable 'data_size' to silence this warning
                unsigned int size, data_size;
                                            ^
                                             = 0
        1 error generated.

    and this fix just initializes 'data_size' to zero before the loop.

    Fixes: 2c865a8a28a1 ("netfilter: nf_tables: add rule blob layout")
    Cc: Pablo Neira Ayuso <pablo@netfilter.org>
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: David Miller <davem@davemloft.net>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>