rcu: Include torture_sched_setaffinity() declaration
JIRA: https://issues.redhat.com/browse/RHEL-34076

commit 3853a720f8bce9c5facb593e817f97659cc0512a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu, 3 Aug 2023 16:40:11 +0200

    rcu: Include torture_sched_setaffinity() declaration

    The prototype for torture_sched_setaffinity() will be moved to a
    different header, which will need to be included from update.c to avoid
    this W=1 warning:

    kernel/rcu/update.c:529:6: error: no previous prototype for 'torture_sched_setaffinity' [-Werror=missing-prototypes]
      529 | long torture_sched_setaffinity(pid_t pid, const struct cpumask *in_mask)

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Joel Fernandes (Google) <joel@joelfernandes.org>
    Signed-off-by: Paul E. McKenney <paulmck@kernel.org>
    Signed-off-by: Frederic Weisbecker <frederic@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>