serial: sunzilog: Mark sunzilog_putchar() __maybe_unused
JIRA: https://issues.redhat.com/browse/RHEL-24205
Conflicts: Simple context diff due to having
           36d2e0758dca ("serial: make uart_console_write->putchar()'s character an unsigned char")
           applied.

commit 159f1f9e46dd09bffee3674d300b02856221e794
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Tue Oct 26 10:04:26 2021 +0200

    serial: sunzilog: Mark sunzilog_putchar() __maybe_unused

    If CONSOLE_POLL=n, CONFIG_SERIAL_SUNZILOG_CONSOLE=n, and CONFIG_SERIO=m:

        drivers/tty/serial/sunzilog.c:1128:13: error: ‘sunzilog_putchar’ defined but not used [-Werror=unused-function]
         1128 | static void sunzilog_putchar(struct uart_port *port, int ch)
              |             ^~~~~~~~~~~~~~~~

    Fix this by marking sunzilog_putchar() __maybe_unused.

    Acked-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: David S. Miller <davem@davemloft.net>
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Link: https://lore.kernel.org/r/20211026080426.2444756-1-geert@linux-m68k.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>