selftests/bpf: Fix prog_tests uprobe_autoattach compilation error
Bugzilla: https://bugzilla.redhat.com/2120968

commit 6a12b8e20d7e72386594a9dbe7bf2d7fae3b3aa6
Author: Artem Savkov <asavkov@redhat.com>
Date:   Thu Apr 21 15:23:17 2022 +0200

    selftests/bpf: Fix prog_tests uprobe_autoattach compilation error
    
    I am getting the following compilation error for prog_tests/uprobe_autoattach.c:
    
      tools/testing/selftests/bpf/prog_tests/uprobe_autoattach.c: In function ‘test_uprobe_autoattach’:
      ./test_progs.h:209:26: error: pointer ‘mem’ may be used after ‘free’ [-Werror=use-after-free]
    
    The value of mem is now used in one of the asserts, which is why it may be
    confusing compilers. However, it is not dereferenced. Silence this by moving
    free(mem) after the assert block.
    
    Fixes: 1717e248014c ("selftests/bpf: Uprobe tests should verify param/return values")
    Signed-off-by: Artem Savkov <asavkov@redhat.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20220421132317.1583867-1-asavkov@redhat.com

Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>