serial: sh-sci: mark OF related data as maybe unused
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 88dcd07d27d1873810cd8423238f3ce4e9bd0bfc
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Fri Mar 10 23:29:56 2023 +0100

    serial: sh-sci: mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      drivers/tty/serial/sh-sci.c:3144:34: error: ‘of_sci_match’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230310222957.315848-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>