net: stmmac: platform: fix build warning when with !CONFIG_PM_SLEEP
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2122226

commit 2a48d96fd58a666ae231c3dd6fe4a458798ac645
Author: Joakim Zhang <qiangqing.zhang@nxp.com>
Date: Thu, 9 Sep 2021 17:23:22 +0800

    Use __maybe_unused for noirq_suspend()/noirq_resume() hooks to avoid
    build warning with !CONFIG_PM_SLEEP:

    >> drivers/net/ethernet/stmicro/stmmac/stmmac_platform.c:796:12: error: 'stmmac_pltfr_noirq_resume' defined but not used [-Werror=unused-function]
         796 | static int stmmac_pltfr_noirq_resume(struct device *dev)
             |            ^~~~~~~~~~~~~~~~~~~~~~~~~
    >> drivers/net/ethernet/stmicro/stmmac/stmmac_platform.c:775:12: error: 'stmmac_pltfr_noirq_suspend' defined but not used [-Werror=unused-function]
         775 | static int stmmac_pltfr_noirq_suspend(struct device *dev)
             |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
       cc1: all warnings being treated as errors

    Fixes: 276aae377206 ("net: stmmac: fix system hang caused by eee_ctrl_timer during suspend/resume")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Joakim Zhang <qiangqing.zhang@nxp.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Mark Salter <msalter@redhat.com>