clk: imx: Select MXC_CLK for i.MX93 clock driver
Bugzilla: http://bugzilla.redhat.com/2137971

commit 7a74e1e49622698fbf106fdc98da55f9e6634c14
Author: Abel Vesa <abel.vesa@nxp.com>
Date:   Tue Mar 15 10:24:46 2022 +0200

    clk: imx: Select MXC_CLK for i.MX93 clock driver

    Most of the i.MX clock generic API is built by selecting MXC_CLK.
    Without it, the i.MX93 clock driver will fail to build:

    aarch64-linux-gnu-ld: drivers/clk/imx/clk-imx93.o:
    in function `imx93_clocks_probe': clk-imx93.c:(.text+0xa8):
    undefined reference to `imx_obtain_fixed_clk_hw'

    So fix this by selecting MXC_CLK for the CLK_IMX93.

    Fixes: 24defbe194b6 ("clk: imx: add i.MX93 clk")
    Signed-off-by: Abel Vesa <abel.vesa@nxp.com>
    Reported-by: kernel test robot <lkp@intel.com>
    Link: https://lore.kernel.org/r/20220315082446.3120850-1-abel.vesa@nxp.com
    Reviewed-by: Peng Fan <peng.fan@nxp.com>
    Signed-off-by: Stephen Boyd <sboyd@kernel.org>

Signed-off-by: Steve Best <sbest@redhat.com>