serial: 8250: omap: convert to modern PM ops
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit ae62c49c0ceff20dc7c1fad4a5b8f91d64b4f628
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 17 22:20:07 2023 +0200

    serial: 8250: omap: convert to modern PM ops

    The new uart_write() function is only called from suspend/resume code, causing
    a build warning when those are left out:

    drivers/tty/serial/8250/8250_omap.c:169:13: error: 'uart_write' defined but not used [-Werror=unused-function]

    Remove the #ifdefs and use the modern pm_ops/pm_sleep_ops and their wrappers
    to let the compiler see where it's used but still drop the dead code.

    Fixes: 398cecc24846 ("serial: 8250: omap: Fix imprecise external abort for omap_8250_pm()")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Tony Lindgren <tony@atomide.com>
    Link: https://lore.kernel.org/r/20230517202012.634386-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>