net: pcs: xpcs: depends on PHYLINK in Kconfig
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2122226

commit ebeae54d3a77e2f6b6b4e18a31bb9a0f7cbff238
Author: Jakub Kicinski <kuba@kernel.org>
Date: Thu, 23 Jun 2022 13:29:33 -0700

    This is yet another attempt at fixing:

    >> ERROR: modpost: "phylink_mii_c22_pcs_encode_advertisement" [drivers/net/pcs/pcs_xpcs.ko] undefined!
    >> ERROR: modpost: "phylink_mii_c22_pcs_decode_state" [drivers/net/pcs/pcs_xpcs.ko] undefined!

    Switch XPCS to be invisible, as Russell points out it's
    "selected" by its consumers. Drop the dependency on MDIO_BUS
    as "depends" is meaningless on "selected" symbols.

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: b47aec885bcd ("net: pcs: xpcs: add CL37 1000BASE-X AN support")
    Link: https://lore.kernel.org/netdev/20220620201915.1195280-1-kuba@kernel.org/
    Link: https://lore.kernel.org/r/20220622083521.0de3ea5c@kernel.org/
    Link: https://lore.kernel.org/r/20220623202933.2341938-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>