kselftest: rtnetlink: fix ip route command typo
JIRA: https://issues.redhat.com/browse/RHEL-31077
Upstream Status: net.git commit 75a50c4f5b95

commit 75a50c4f5b957a34dedb7c8cce52b582a9162828
Author: Paolo Abeni <pabeni@redhat.com>
Date:   Thu Nov 16 18:01:41 2023 +0100

    kselftest: rtnetlink: fix ip route command typo

    The blamed commit below introduced a typo causing 'gretap' test-case
    failures:

    ./rtnetlink.sh  -t kci_test_gretap -v
    COMMAND: ip link add name test-dummy0 type dummy
    COMMAND: ip link set test-dummy0 up
    COMMAND: ip netns add testns
    COMMAND: ip link help gretap 2>&1 | grep -q '^Usage:'
    COMMAND: ip -netns testns link add dev gretap00 type gretap seq key 102 local 172.16.1.100 remote 172.16.1.200
    COMMAND: ip -netns testns addr add dev gretap00 10.1.1.100/24
    COMMAND: ip -netns testns link set dev gretap00 ups
        Error: either "dev" is duplicate, or "ups" is a garbage.
    COMMAND: ip -netns testns link del gretap00
    COMMAND: ip -netns testns link add dev gretap00 type gretap external
    COMMAND: ip -netns testns link del gretap00
    FAIL: gretap

    Fix it by using the correct keyword.

    Fixes: 9c2a19f71515 ("kselftest: rtnetlink.sh: add verbose flag")
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>
    Reviewed-by: Hangbin Liu <liuhangbin@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Hangbin Liu <haliu@redhat.com>