pata: ixp4xx: Add explicit include for of.h
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 5d6f12c381071d2206a2b73140f7f1e7c86bc104
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:20 2023 -0500

    pata: ixp4xx: Add explicit include for of.h

    With linux/acpi.h no longer implicitly including of.h, add an explicit
    include of of.h to fix the following error:

    drivers/ata/pata_ixp4xx_cf.c:258:15: error: implicit declaration of function 'of_property_read_u32_index'; did you mean 'fwnode_property_read_u32_array'? [-Werror=implicit-function-declaration]

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>