mm: compaction: remove incorrect #ifdef checks
JIRA: https://issues.redhat.com/browse/RHEL-27741

commit b3f312c4815d7acf6c7f88f921544626c31bd24a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Mar 29 10:02:41 2023 +0200

    mm: compaction: remove incorrect #ifdef checks

    Without CONFIG_SYSCTL, the compiler warns about a few unused functions:

    mm/compaction.c:3076:12: error: 'proc_dointvec_minmax_warn_RT_change' defined but not used [-Werror=unused-function]
    mm/compaction.c:2780:12: error: 'sysctl_compaction_handler' defined but not used [-Werror=unused-function]
    mm/compaction.c:2750:12: error: 'compaction_proactiveness_sysctl_handler' defined but not used [-Werror=unused-function]

    The #ifdef is actually not necessary here, as the alternative
    register_sysctl_init() stub function does not use its argument, which
    lets the compiler drop the rest implicitly, while avoiding the warning.

    Fixes: c521126610c3 ("mm: compaction: move compaction sysctl to its own file")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>