tools/bpf: Rename 'struct event' to avoid naming conflict
Bugzilla: https://bugzilla.redhat.com/2069046

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 88a71086c48ae98e93c0208044827621e9717f7e
Author: Naveen N. Rao <naveen.n.rao@linux.vnet.ibm.com>
Date:   Thu Jan 6 17:15:08 2022 +0530

    tools/bpf: Rename 'struct event' to avoid naming conflict

    On ppc64le, trying to build bpf seltests throws the below warning:
      In file included from runqslower.bpf.c:5:
      ./runqslower.h:7:8: error: redefinition of 'event'
      struct event {
             ^
      /home/naveen/linux/tools/testing/selftests/bpf/tools/build/runqslower/vmlinux.h:156602:8:
      note: previous definition is here
      struct event {
             ^

    This happens since 'struct event' is defined in
    drivers/net/ethernet/alteon/acenic.h . Rename the one in runqslower to a
    more appropriate 'runq_event' to avoid the naming conflict.

    Signed-off-by: Naveen N. Rao <naveen.n.rao@linux.vnet.ibm.com>
    Acked-by: Daniel Borkmann <daniel@iogearbox.net>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/c13cb3767d26257ca4387b8296b632b433a58db6.1641468127.git.naveen.n.rao@linux.vnet.ibm.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>