drm: fb_helper: fix CONFIG_FB dependency
Bugzilla: http://bugzilla.redhat.com/1986223

commit 606b102876e3741851dfb09d53f3ee57f650a52c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 27 16:28:02 2021 +0200

    drm: fb_helper: fix CONFIG_FB dependency

    With CONFIG_FB=m and CONFIG_DRM=y, we get a link error in the fb helper:

    aarch64-linux-ld: drivers/gpu/drm/drm_fb_helper.o: in function `drm_fb_helper_alloc_fbi':
    (.text+0x10cc): undefined reference to `framebuffer_alloc'

    Tighten the dependency so it is only allowed in the case that DRM can
    link against FB.

    Fixes: f611b1e7624c ("drm: Avoid circular dependencies for CONFIG_FB")
    Link: https://lore.kernel.org/all/20210721152211.2706171-1-arnd@kernel.org/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
    Link: https://patchwork.freedesktop.org/patch/msgid/20210927142816.2069269-1-arnd@kernel.org

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>