iio: adc: ad7292: Add explicit include for of.h
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit ff7f85e35479243e86c31726bb2c54b24fef07cd
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:15 2023 -0500

    iio: adc: ad7292: Add explicit include for of.h

    With linux/acpi.h no longer implicitly including of.h, add an explicit
    include of of.h to fix the following error:

    drivers/iio/adc/ad7292.c:307:9: error: implicit declaration of function 'for_each_available_child_of_node'; did you mean 'fwnode_for_each_available_child_node'? [-Werror=implicit-function-declaration]

    Acked-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
    Acked-by: Marcelo Schmitt <marcelo.schmitt1@gmail.com>
    Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
    Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>