serial: pic32: make SERIAL_PIC32_CONSOLE depend on SERIAL_PIC32=y
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 86b9602f8203b7b3b5a189fba759b58c9d6f378e
Author: Jiri Slaby <jirislaby@kernel.org>
Date:   Thu Apr 21 12:17:07 2022 +0200

    serial: pic32: make SERIAL_PIC32_CONSOLE depend on SERIAL_PIC32=y

    pic32_uart contains this:
      #ifdef CONFIG_SERIAL_PIC32_CONSOLE
      ...
      console_initcall(pic32_console_init);
      ...
      core_initcall(pic32_late_console_init);
      ...
      #endif
      ...
      arch_initcall(pic32_uart_init);

    When the driver is built as module, all three above become
    module_init(). So if SERIAL_PIC32_CONSOLE is set while SERIAL_PIC32=m,
    it results in the following build error:
      In file included from include/linux/device/driver.h:21,
                       from include/linux/device.h:32,
                       from include/linux/platform_device.h:13,
                       from drivers/tty/serial/pic32_uart.c:12:
      include/linux/module.h:131:49: error: redefinition of '__inittest'

    So make sure SERIAL_PIC32_CONSOLE can be set only when SERIAL_PIC32=y --
    similar as for other drivers.

    Signed-off-by: Jiri Slaby <jslaby@suse.cz>
    Link: https://lore.kernel.org/r/20220421101708.5640-7-jslaby@suse.cz
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>