s390/vx: remove __uint128_t type from __vector128 struct again
JIRA: https://issues.redhat.com/browse/RHEL-29741

commit 55d169c87db1d0faa95313809f18f8b49cafdd75
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Fri Feb 10 14:09:38 2023 +0100

    s390/vx: remove __uint128_t type from __vector128 struct again

    The __uint128_t member was only added for future convenience to the
    __vector128 struct. However this is a uapi header file, 31/32 bit (aka
    compat layer) is still supported, but doesn't know anything about this
    type:

    /usr/include/asm/types.h:27:17: error: unknown type name __uint128_t
       27 |                 __uint128_t v;

    Therefore remove it again.

    Fixes: b0b7b43fcc46 ("s390/vx: add 64 and 128 bit members to __vector128 struct")
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>

Signed-off-by: Thomas Huth <thuth@redhat.com>