modpost: fix removing numeric suffixes
Jira: http://issues.redhat.com/28063

commit b5beffa20d83c4e15306c991ffd00de0d8628338
Author: Alexander Lobakin <alexandr.lobakin@intel.com>
Date:   Tue May 24 17:27:18 2022 +0200

    modpost: fix removing numeric suffixes

    With the `-z unique-symbol` linker flag or any similar mechanism,
    it is possible to trigger the following:

    ERROR: modpost: "param_set_uint.0" [vmlinux] is a static EXPORT_SYMBOL

    The reason is that for now the condition from remove_dot():

    if (m && (s[n + m] == '.' || s[n + m] == 0))

    which was designed to test if it's a dot or a '\0' after the suffix
    is never satisfied.
    This is due to that `s[n + m]` always points to the last digit of a
    numeric suffix, not on the symbol next to it (from a custom debug
    print added to modpost):

    param_set_uint.0, s[n + m] is '0', s[n + m + 1] is '\0'

    So it's off-by-one and was like that since 2014.

    Fix this for the sake of any potential upcoming features, but don't
    bother stable-backporting, as it's well hidden -- apart from that
    LD flag, it can be triggered only with GCC LTO which never landed
    upstream.

    Fixes: fcd38ed0ff26 ("scripts: modpost: fix compilation warning")
    Signed-off-by: Alexander Lobakin <alexandr.lobakin@intel.com>
    Reviewed-by: Petr Mladek <pmladek@suse.com>
    Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>