dpll: fix build failure due to rcu_dereference_check() on unknown type
JIRA: https://issues.redhat.com/browse/RHEL-32098

Upstream commit(s):
commit 640f41ed33b5a420e05daf395afae85e6b20c003
Author: Eric Dumazet <edumazet@google.com>
Date:   Thu Feb 29 11:05:15 2024 -0800

    dpll: fix build failure due to rcu_dereference_check() on unknown type

    Tasmiya reports that their compiler complains that we deref
    a pointer to unknown type with rcu_dereference_rtnl():

    include/linux/rcupdate.h:439:9: error: dereferencing pointer to incomplete type ‘struct dpll_pin’

    Unclear what compiler it is, at the moment, and we can't report
    but since DPLL can't be a module - move the code from the header
    into the source file.

    Fixes: 0d60d8df6f49 ("dpll: rely on rcu for netdev_dpll_pin()")
    Reported-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
    Link: https://lore.kernel.org/all/3fcf3a2c-1c1b-42c1-bacb-78fdcd700389@linux.vnet.ibm.com/
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Link: https://lore.kernel.org/r/20240229190515.2740221-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Petr Oros <poros@redhat.com>