radix tree: remove unused variable
commit d59070d1076ec5114edb67c87658aeb1d691d381
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Aug 11 15:10:13 2023 +0200

    radix tree: remove unused variable

    Recent versions of clang warn about an unused variable, though older
    versions saw the 'slot++' as a use and did not warn:

    radix-tree.c:1136:50: error: parameter 'slot' set but not used [-Werror,-Wunused-but-set-parameter]

    It's clearly not needed any more, so just remove it.

    Link: https://lkml.kernel.org/r/20230811131023.2226509-1-arnd@kernel.org
    Fixes: 3a08cd52c37c7 ("radix tree: Remove multiorder support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Matthew Wilcox <willy@infradead.org>
    Cc: Nathan Chancellor <nathan@kernel.org>
    Cc: Nick Desaulniers <ndesaulniers@google.com>
    Cc: Peng Zhang <zhangpeng.00@bytedance.com>
    Cc: Rong Tao <rongtao@cestc.cn>
    Cc: Tom Rix <trix@redhat.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

JIRA: https://issues.redhat.com/browse/RHEL-5619
Signed-off-by: Nico Pache <npache@redhat.com>