libbpf: Add pr_warn() for EINVAL cases in linker_sanity_check_elf
JIRA: https://issues.redhat.com/browse/RHEL-23644

commit 32fa058398624166dd04ff4af49cfef69c94abbc
Author: Sergei Trofimovich <slyich@gmail.com>
Date:   Fri Dec 8 21:51:00 2023 +0000

    libbpf: Add pr_warn() for EINVAL cases in linker_sanity_check_elf
    
    Before the change on `i686-linux` `systemd` build failed as:
    
        $ bpftool gen object src/core/bpf/socket_bind/socket-bind.bpf.o src/core/bpf/socket_bind/socket-bind.bpf.unstripped.o
        Error: failed to link 'src/core/bpf/socket_bind/socket-bind.bpf.unstripped.o': Invalid argument (22)
    
    After the change it fails as:
    
        $ bpftool gen object src/core/bpf/socket_bind/socket-bind.bpf.o src/core/bpf/socket_bind/socket-bind.bpf.unstripped.o
        libbpf: ELF section #9 has inconsistent alignment addr=8 != d=4 in src/core/bpf/socket_bind/socket-bind.bpf.unstripped.o
        Error: failed to link 'src/core/bpf/socket_bind/socket-bind.bpf.unstripped.o': Invalid argument (22)
    
    Now it's slightly easier to figure out what is wrong with an ELF file.
    
    Signed-off-by: Sergei Trofimovich <slyich@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Eduard Zingerman <eddyz87@gmail.com>
    Link: https://lore.kernel.org/bpf/20231208215100.435876-1-slyich@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>