redhat/Makefile: Drop quotation marks around string definitions
Bugzilla: INTERNAL
Upstream Status: RHEL only, https://gitlab.com/cki-project/kernel-ark

commit 15bd2162283cc169d272a636505e162aca62a948
Author: Prarit Bhargava <prarit@redhat.com>
Date:   Mon May 16 18:37:17 2022 -0400

    redhat/Makefile: Drop quotation marks around string definitions

    dzickus reports that 'make dist-srpm-gcov' doesn't work anymore.  Not only
    is an error reported,

    error: line 555: Illegal char '"' (0x22) in: Release: 0.rc7.53".gcov".fc35
    error: query of specfile /home/prarit/git-kernel/kernel-ark/redhat/rpm/SOURCES/kernel.spec failed, can't parse

    but the resulting specfile does not contain '%define _with_gcov 1'.

    Exporting the Makefile variables into the scripts results in quotation
    marks now being interpreted as part of the string.  As can be seen in the
    error above the quotation mark is the problem.

    Drop quotation marks around string definitions.

    Reported-by: Don Zickus <dzickus@redhat.com>
    Signed-off-by: Prarit Bhargava <prarit@redhat.com>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>