regulator: lp872x: Remove lp872x_dvs_state
Bugzilla: http://bugzilla.redhat.com/2071777

commit 061514dbfb79910ef60eb40dd9fc528be3f45d62
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Oct 18 17:43:35 2021 -0700

    regulator: lp872x: Remove lp872x_dvs_state

    After this driver was converted to gpiod, clang started warning:

    vers/regulator/lp872x.c:689:57: error: implicit conversion from
    enumeration type 'enum lp872x_dvs_state' to different enumeration type
    'enum gpiod_flags' [-Werror,-Wenum-conversion]
            dvs->gpio = devm_gpiod_get_optional(lp->dev, "ti,dvs", pinstate);
                        ~~~~~~~~~~~~~~~~~~~~~~~                    ^~~~~~~~
    1 error generated.

    lp872x_dvs_state was updated to have values from gpiod_flags but this is
    not enough to avoid an implicit conversion warning from either GCC or
    clang (although GCC enables this warning under -Wextra instead of -Wall
    like clang so it is not seen under normal builds).

    Eliminate lp872x_dvs_state in favor of using gpiod_flags everywhere so
    that there is no more warning about an implicit conversion.

    Fixes: 72bf80cf09c4 ("regulator: lp872x: replacing legacy gpio interface for gpiod")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1481
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20211019004335.193492-1-nathan@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Steve Best <sbest@redhat.com>