tty: serial: atmel: Add COMMON_CLK dependency to SERIAL_ATMEL
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 468cdabe93c5fa969de65752e38c31f07a5e048d
Author: Sergiu Moga <sergiu.moga@microchip.com>
Date:   Mon Sep 26 17:32:45 2022 +0300

    tty: serial: atmel: Add COMMON_CLK dependency to SERIAL_ATMEL

    Now that the driver makes use of `__clk_is_enabled()` in order to
    know whether a `clk_disable_unprepare()` is needed or not on the
    GCLK, a new dependency has been introduced: COMMON_CLK. If this
    `CONFIG_COMMON_CLK` is not enabled, whatever config may have this
    driver enabled without COMMON_CLK then an undefined reference to
    `__clk_is_enabled()` will be issued by the linker.

    Thus, make sure that, unless `CONFIG_COMMON_CLK` is enabled, this
    driver is not compiled.

    Fixes: 5e3ce1f26129 ("tty: serial: atmel: Make the driver aware of the existence of GCLK")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Sergiu Moga <sergiu.moga@microchip.com>
    Acked-by: Nicolas Ferre <nicolas.ferre@microchip.com>
    Link: https://lore.kernel.org/r/20220926143244.485578-1-sergiu.moga@microchip.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>