Add python3-setuptools buildreq for perf
Bugzilla: INTERNAL
Upstream Status: RHEL only, https://gitlab.com/cki-project/kernel-ark

commit d86c03e2ce1fb991a8a20b65e07e756124b36aa4
Author: Justin M. Forbes <jforbes@fedoraproject.org>
Date:   Wed Aug 10 11:25:25 2022 -0500

    Add python3-setuptools buildreq for perf

    With the 6.0 updates for perf, the build fails with a missing
    ModuleNotFoundError: No module named 'setuptools' if we don't have
    python3-setuptools as a buildreq.

    Signed-off-by: Justin M. Forbes <jforbes@fedoraproject.org>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>