scsi: qla4xxx: Remove unused 'count' variable
JIRA: https://issues.redhat.com/browse/RHEL-16725

commit 3d2efb5470f58707a9120720af238d1dacdf77b5
Author: Tom Rix <trix@redhat.com>
Date:   Fri Mar 31 13:57:57 2023 -0400

    scsi: qla4xxx: Remove unused 'count' variable

    clang with W=1 reports:

    drivers/scsi/qla4xxx/ql4_isr.c:475:11: error: variable
      'count' set but not used [-Werror,-Wunused-but-set-variable]
            uint32_t count = 0;
                     ^
    This variable is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230331175757.1860780-1-trix@redhat.com
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Chris Leech <cleech@redhat.com>