memblock: fix memblock_phys_alloc() section mismatch error
commit d7f55471db2719629f773c2d6b5742a69595bfd3
Author: Jackie Liu <liuyun01@kylinos.cn>
Date:   Fri Dec 17 10:07:54 2021 +0800

    memblock: fix memblock_phys_alloc() section mismatch error

    Fix modpost Section mismatch error in memblock_phys_alloc()

    [...]
    WARNING: modpost: vmlinux.o(.text.unlikely+0x1dcc): Section mismatch in reference
    from the function memblock_phys_alloc() to the function .init.text:memblock_phys_alloc_range()
    The function memblock_phys_alloc() references
    the function __init memblock_phys_alloc_range().
    This is often because memblock_phys_alloc lacks a __init
    annotation or the annotation of memblock_phys_alloc_range is wrong.

    ERROR: modpost: Section mismatches detected.
    Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.
    [...]

    memblock_phys_alloc() is a one-line wrapper, make it __always_inline to
    avoid these section mismatches.

    Reported-by: k2ci <kernel-bot@kylinos.cn>
    Suggested-by: Mike Rapoport <rppt@kernel.org>
    Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
    [rppt: slightly massaged changelog ]
    Signed-off-by: Mike Rapoport <rppt@linux.ibm.com>
    Link: https://lore.kernel.org/r/20211217020754.2874872-1-liu.yun@linux.dev

JIRA: https://issues.redhat.com/browse/RHEL-5619
Signed-off-by: Nico Pache <npache@redhat.com>