coresight: dummy: Update type of mode parameter in dummy_{sink,source}_enable()
JIRA: https://issues.redhat.com/browse/RHEL-21456

commit 185891f03f712639c082e08fc9986ff214b5d617
Author: Nathan Chancellor <nathan@kernel.org>
Date: Fri, 16 Jun 2023 09:41:30 -0700

    Clang's kernel Control Flow Integrity (kCFI) is a compiler-based
    security mitigation that ensures the target of an indirect function call
    matches the expected type of the call and trapping if they do not match
    exactly. The warning -Wincompatible-function-pointer-types-strict aims
    to catch these issues at compile time, which reveals:

      drivers/hwtracing/coresight/coresight-dummy.c:53:12: error: incompatible function pointer types initializing 'int (*)(struct coresight_device *, struct perf_event *, enum cs_mode)' with an expression of type 'int (struct coresight_device *, struct perf_event *, u32)' (aka 'int (struct coresight_device *, struct perf_event *, unsigned int)') [-Werror,-Wincompatible-function-pointer-types-strict]
         53 |         .enable = dummy_source_enable,
            |                   ^~~~~~~~~~~~~~~~~~~
      drivers/hwtracing/coresight/coresight-dummy.c:62:12: error: incompatible function pointer types initializing 'int (*)(struct coresight_device *, enum cs_mode, void *)' with an expression of type 'int (struct coresight_device *, u32, void *)' (aka 'int (struct coresight_device *, unsigned int, void *)') [-Werror,-Wincompatible-function-pointer-types-strict]
         62 |         .enable = dummy_sink_enable,
            |                   ^~~~~~~~~~~~~~~~~
      2 errors generated.

    Commit 9fa3682869d4 ("coresight: Use enum type for cs_mode wherever
    possible") updated the type of the mode parameter in the prototype but
    this driver was not introduced until commit 9d3ba0b6c056 ("Coresight:
    Add coresight dummy driver") and 'int' is ABI compatible with 'enum
    cs_mode', so there is no warning from regular
    -Wincompatible-function-pointer-types.

    Adjust the type of the mode parameter in the callback implementations in
    the coresight dummy driver to match the prototype, clearing up the
    warning and avoiding kCFI failures at runtime.

    Fixes: 9d3ba0b6c056 ("Coresight: Add coresight dummy driver")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Suzuki K Poulose <suzuki.poulose@arm.com>
    Link: https://lore.kernel.org/r/20230616-coresight-dummy-fix-kcfi-warnings-v1-1-c55c64f8f0f5@kernel.org

Signed-off-by: Mark Salter <msalter@redhat.com>