bug: Have __warn() prototype defined unconditionally
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2121207

commit 1fa568e26f001e951b634d62ef3accdc80a87c7b
Author: Shida Zhang <zhangshida@kylinos.cn>
Date:   Tue Apr 26 11:20:07 2022 +0800

    bug: Have __warn() prototype defined unconditionally

    The __warn() prototype is declared in CONFIG_BUG scope but the function
    definition in panic.c is unconditional. The IBT enablement started using
    it unconditionally but a CONFIG_X86_KERNEL_IBT=y, CONFIG_BUG=n .config
    will trigger a

      arch/x86/kernel/traps.c: In function ‘__exc_control_protection’:
      arch/x86/kernel/traps.c:249:17: error: implicit declaration of function \
              ‘__warn’; did you mean ‘pr_warn’? [-Werror=implicit-function-declaration]

    Pull up the declarations so that they're unconditionally visible too.

      [ bp: Rewrite commit message. ]

    Fixes: 991625f3dd2c ("x86/ibt: Add IBT feature, MSR and #CP handling")
    Suggested-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Signed-off-by: Shida Zhang <zhangshida@kylinos.cn>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Link: https://lore.kernel.org/r/20220426032007.510245-1-starzhangzsd@gmail.com

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>