ASoC: ti: ams-delta: Fix cx81801_receive() argument types
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit b3fa3cf02e3ce92d32bfdeedd5a6bd0825f55a14
Author: Janusz Krzysztofik <jmkrzyszt@gmail.com>
Date:   Sat Oct 7 23:38:18 2023 +0200

    ASoC: ti: ams-delta: Fix cx81801_receive() argument types

    Since types of arguments accepted by tty_ldis_ops::receive_buf() have
    changed, the driver no longer builds.

    .../linux/sound/soc/ti/ams-delta.c:403:24: error: initialization of 'void (*)(struct tty_struct *, const u8 *, const u8 *, size_t)' {aka 'void (*)(struct tty_struct *, const unsigned char *, const unsigned char *, unsigned int)'} from incompatible pointer type 'void (*)(struct tty_struct *, const u8 *, const char *, int)' {aka 'void (*)(struct tty_struct *, const unsigned char *, const char *, int)'} [-Werror=incompatible-pointer-types]
      403 |         .receive_buf = cx81801_receive,

    Fix it.

    Fixes: e8161447bb0c ("tty: make tty_ldisc_ops::*buf*() hooks operate on size_t")
    Fixes: 892bc209f250 ("tty: use u8 for flags")
    Signed-off-by: Janusz Krzysztofik <jmkrzyszt@gmail.com>
    Link: https://lore.kernel.org/r/20231007213820.376360-1-jmkrzyszt@gmail.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>