module: stats: include uapi/linux/module.h
Jira: http://issues.redhat.com/28063

commit 635dc38314c75c5727711d896d4c71ec92f6f20b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Apr 18 00:02:46 2023 +0200

    module: stats: include uapi/linux/module.h

    MODULE_INIT_COMPRESSED_FILE is defined in the uapi header, which
    is not included indirectly from the normal linux/module.h, but
    has to be pulled in explicitly:

    kernel/module/stats.c: In function 'mod_stat_bump_invalid':
    kernel/module/stats.c:227:14: error: 'MODULE_INIT_COMPRESSED_FILE' undeclared (first use in this function)
      227 |  if (flags & MODULE_INIT_COMPRESSED_FILE)
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>