redhat: fix chronological order in the changelog file
Bugzilla: INTERNAL
Upstream Status: RHEL only

commit 0e6715114ede1fdda91dbc2a44eb6a89a57b31be
Author: Herton R. Krzesinski <herton@redhat.com>
Date:   Fri Sep 17 15:19:22 2021 -0300

    redhat: fix chronological order in the changelog file

    Bugzilla: INTERNAL
    Upstream Status: RHEL-only

    Right now eg. when creating an src.rpm, rpm throws this:
    error: %changelog not in descending chronological order

    This is caused by last merge from 9-beta having included
    new changelog entries with a date newer than the next
    entry.

    This is mostly a warning and does not prevent src.rpm creation
    or the build. The problem is that tools like centpkg gets
    confused treating it as a real error and eg. its build command
    fails due it.

    Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>