ynl: allow to encode u8 attr
JIRA: https://issues.redhat.com/browse/RHEL-30656

commit 8da3a5598f75cd0361e11b6d74697084380eb4b0
Author: Jiri Pirko <jiri@nvidia.com>
Date:   Wed Mar 22 16:42:42 2023 +0100

    ynl: allow to encode u8 attr

    Playing with dpll netlink, I came across following issue:
    $ sudo ./tools/net/ynl/cli.py --spec Documentation/netlink/specs/dpll.yaml --do pin-set --json '{"id": 0, "pin-idx": 1, "pin-state": 1}'
    Traceback (most recent call last):
      File "tools/net/ynl/cli.py", line 52, in <module>
        main()
      File "tools/net/ynl/cli.py", line 40, in main
        reply = ynl.do(args.do, attrs)
      File "tools/net/ynl/lib/ynl.py", line 520, in do
        return self._op(method, vals)
      File "tools/net/ynl/lib/ynl.py", line 476, in _op
        msg += self._add_attr(op.attr_set.name, name, value)
      File "tools/net/ynl/lib/ynl.py", line 344, in _add_attr
        raise Exception(f'Unknown type at {space} {name} {value} {attr["type"]}')
    Exception: Unknown type at dpll pin-state 1 u8

    I'm not that familiar with ynl code, but from a quick peek, I suspect
    that couple other types are missing for both encoding and decoding.
    Ignoring those here as I'm scratching my local itch only.

    Fix the issue by adding u8 attr packing.

    Signed-off-by: Jiri Pirko <jiri@nvidia.com>
    Link: https://lore.kernel.org/r/20230322154242.1739136-1-jiri@resnulli.us
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>