KVM: selftests: Delete superfluous, unused "stage" variable in AMX test
JIRA: https://issues.redhat.com/browse/RHEL-32430

commit 46fee9e38995af9ae16a8cc7d05031486d44cf35
Author: Sean Christopherson <seanjc@google.com>
Date:   Tue Jan 9 14:03:02 2024 -0800

    KVM: selftests: Delete superfluous, unused "stage" variable in AMX test

    Delete the AMX's tests "stage" counter, as the counter is no longer used,
    which makes clang unhappy:

      x86_64/amx_test.c:224:6: error: variable 'stage' set but not used
              int stage, ret;
                  ^
      1 error generated.

    Note, "stage" was never really used, it just happened to be dumped out by
    a (failed) assertion on run->exit_reason, i.e. the AMX test has no concept
    of stages, the code was likely copy+pasted from a different test.

    Fixes: c96f57b08012 ("KVM: selftests: Make vCPU exit reason test assertion common")
    Reviewed-by: Jim Mattson <jmattson@google.com>
    Link: https://lore.kernel.org/r/20240109220302.399296-1-seanjc@google.com
    Signed-off-by: Sean Christopherson <seanjc@google.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>