tools: ynl: avoid dict errors on older Python versions
JIRA: https://issues.redhat.com/browse/RHEL-30656

commit 081e8df6819997eae236f75dd52f0c147c4be939
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Wed May 24 10:07:12 2023 -0700

    tools: ynl: avoid dict errors on older Python versions

    Python 3.9.0 or newer supports combining dicts() with |,
    but older versions of Python are still used in the wild
    (e.g. on CentOS 8, which goes EoL May 31, 2024).
    With Python 3.6.8 we get:

      TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

    Use older syntax. Tested with non-legacy families only.

    Fixes: f036d936ca57 ("tools: ynl: Add fixed-header support to ynl")
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Reviewed-by: Donald Hunter <donald.hunter@gmail.com>
    Tested-by: Donald Hunter <donald.hunter@gmail.com>
    Link: https://lore.kernel.org/r/20230524170712.2036128-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>