samples: bpf: Fix linking xdp_router_ipv4 after migration
Bugzilla: https://bugzilla.redhat.com/2120968

commit fc843ccd8e4c084fa5d605a876db2d3a3c38be88
Author: Alexander Lobakin <alexandr.lobakin@intel.com>
Date:   Mon Apr 4 13:54:51 2022 +0200

    samples: bpf: Fix linking xdp_router_ipv4 after migration
    
    Users of the xdp_sample_user infra should be explicitly linked
    with the standard math library (`-lm`). Otherwise, the following
    happens:
    
    /usr/bin/ld: xdp_sample_user.c:(.text+0x59fc): undefined reference to `ceil'
    /usr/bin/ld: xdp_sample_user.c:(.text+0x5a0d): undefined reference to `ceil'
    /usr/bin/ld: xdp_sample_user.c:(.text+0x5adc): undefined reference to `floor'
    /usr/bin/ld: xdp_sample_user.c:(.text+0x5b01): undefined reference to `ceil'
    /usr/bin/ld: xdp_sample_user.c:(.text+0x5c1e): undefined reference to `floor'
    /usr/bin/ld: xdp_sample_user.c:(.text+0x5c43): undefined reference to `ceil
    [...]
    
    That happened previously, so there's a block of linkage flags in the
    Makefile. xdp_router_ipv4 has been transferred to this infra quite
    recently, but hasn't been added to it. Fix.
    
    Fixes: 85bf1f51691c ("samples: bpf: Convert xdp_router_ipv4 to XDP samples helper")
    Signed-off-by: Alexander Lobakin <alexandr.lobakin@intel.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20220404115451.1116478-1-alexandr.lobakin@intel.com

Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>