[PATCH] misc: rtsx: conditionally build rtsx_pm_power_saving()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=212077
Upstream Status: https://github.com/torvalds/linux.git
Commit 2c9ae453543c ("misc: rtsx: conditionally build rtsx_pm")
Author: Tom Rix <trix@redhat.com>
Date: Sun, 13 Feb 2022 09:19:07 -0800

Original Description:

On s390 allyesconfig, there is this build error
rtsx_pcr.c:1084:13: error: 'rtsx_pm_power_saving'
  defined but not used
 1084 | static void rtsx_pm_power_saving(struct rtsx_pcr *pcr)
      |             ^~~~~~~~~~~~~~~~~~~~

rtsx_pm_power_saving() is only used by rtsx_pci_runtime_idle()
which is conditional on CONFIG_PM.  So conditionally build
rtsx_pm_power_saving() and the similar
rtsx_comm_pm_power_saving() and rtsx_enable_aspm().

Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20220213171907.2786442-1-trix@redhat.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Mark Pearson <mapearso@redhat.com>