net/mlx5e: Fix build warning, detected write beyond size of field
Bugzilla: https://bugzilla.redhat.com/2112947
Bugzilla: http://bugzilla.redhat.com/2049859
Upstream-status: v5.18-rc1

commit 2af7e566a8616c278e1d7287ce86cd3900bed943
Author: Saeed Mahameed <saeedm@nvidia.com>
Date:   Tue Mar 22 10:22:24 2022 -0700

    net/mlx5e: Fix build warning, detected write beyond size of field

    When merged with Linus tree, the cited patch below will cause the
    following build warning:

    In function 'fortify_memset_chk',
        inlined from 'mlx5e_xmit_xdp_frame' at drivers/net/ethernet/mellanox/mlx5/core/en/xdp.c:438:3:
    include/linux/fortify-string.h:242:25: error: call to '__write_overflow_field' declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
      242 |                         __write_overflow_field(p_size_field, size);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Fix that by grouping the fields to memeset in struct_group() to avoid
    the false alarm.

    Fixes: 9ded70fa1d81 ("net/mlx5e: Don't prefill WQEs in XDP SQ in the multi buffer mode")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Suggested-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Link: https://lore.kernel.org/r/20220322172224.31849-1-saeed@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>