xsk: Fix clang build error in __xp_alloc
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2074113

commit 3103836496e75095ac208cc180a9fe8f7ff33fd8
Author: Magnus Karlsson <magnus.karlsson@intel.com>
Date:   Wed Sep 29 08:14:03 2021 +0200

    xsk: Fix clang build error in __xp_alloc

    Fix a build error with clang in __xp_alloc():

      [...]
      net/xdp/xsk_buff_pool.c:465:15: error: variable 'xskb' is uninitialized
      when used here [-Werror,-Wuninitialized]
                              xp_release(xskb);
                                         ^~~~

    This is correctly detected by clang, but not gcc. In fact, the xp_release()
    statement should not be there at all in the refactored code, just remove it.

    Fixes: 94033cd8e73b ("xsk: Optimize for aligned case")
    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Magnus Karlsson <magnus.karlsson@intel.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Maciej Fijalkowski <maciej.fijalkowski@intel.com>
    Link: https://lore.kernel.org/bpf/20210929061403.8587-1-magnus.karlsson@gmail.com

Signed-off-by: Ivan Vecera <ivecera@redhat.com>